services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio_server
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001" # порт для панели управления
    volumes:
      - minio_data:/data
    networks:
      - backend_network

  # Redis
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - backend_network
    volumes:
      - redis_data:/data

# Настройка сети
networks:
  backend_network:
    driver: bridge

# Настройка томов
volumes:
  postgres_data:
  minio_data:
  redis_data: